---
title: "Reproducibility Supplement"
format: html
---


```{r}
#| label: libraries

library(conflicted)

conflicts_prefer(dplyr::filter)

library(BMTCensusManuscript)
library(tidyverse)
library(timetk)
library(rsample)
library(parsnip)
library(workflows)
library(workflowsets)
library(modeltime)
library(poissonreg)
library(parallel)
library(future)
library(dials)
library(recipes)
library(tune)
library(yardstick)

theme_set(theme_minimal())
```

```{r}
#| label: run settings

run_split <- FALSE
run_cv <- FALSE
run_tune <- FALSE
run_test <- FALSE
```

## Split Data

Load data

```{r}
#| label: load data

train_test_split_date <- as_date("2022-09-30")

census_data <- readRDS("manuscript/data/census.rds")
admission_data <- readRDS("manuscript/data/admissions.rds")
scheduled_admissions <- readRDS("manuscript/data/scheduled_admissions.rds") |>
  count(transplant_type, date, admission_date, name = "scheduled")
```

Split census data

```{r}
#| label: split census

census_data_split <- census_data |>
    # Don't need these extra columns
    select(!any_of(c("admission_type", "admit_sched_date"))) |>
    train_test_split(split_date = train_test_split_date)
```

Split admissions data

```{r}
#| label: split admissions

test_length <- as.numeric(max(admission_data$date) - train_test_split_date, unit = "days")

admissions_ts_split <- admission_data |>
  time_series_split(
    date_var = date,
    assess = test_length,
    cumulative = TRUE
  )
```

```{r}
#| label: save train test data
#| eval: !expr run_split

discharge_train <- training(census_data_split)
admission_train <- training(admissions_ts_split)

discharge_test <- testing(census_data_split)
admission_test <- testing(admissions_ts_split)

save_data(census_data_split, "manuscript/data-split/census.rds")
save_data(admissions_ts_split, "manuscript/data-split/admissions.rds")
```


```{r}
#| label: load train test data
#| eval: !expr (!run_split)
#| include: false

discharge_train <- readRDS("manuscript/data-split/census.rds") |> training()
admission_train <- readRDS("manuscript/data-split/admissions.rds") |> training()

discharge_test <- readRDS("manuscript/data-split/census.rds") |> testing()
admission_test <- readRDS("manuscript/data-split/admissions.rds") |> testing()
```

## Model Selection

Define models

```{r}
#| label: models

discharge_models <- list(
  logistic = logistic_reg(),
  xgboost = boost_tree(mode = "classification")
)

discharge_wflowset <- workflow_set(
  preproc = list(baseline = discharge_rec(discharge_train)),
  models = discharge_models
)

admission_wflow_poisson <- workflow(
  preprocessor = admission_rec(admission_train, type = "poisson"),
  spec = poisson_reg("regression")
)

admission_wflow_xgb <- workflow(
  preprocessor = admission_rec(admission_train, type = "xgb"),
  spec = boost_tree("regression") |>
    set_engine("xgboost", objective = "count:poisson")
)

admission_model_tbl <- modeltime_table(
  fit(admission_wflow_poisson, admission_train),
  fit(admission_wflow_xgb, admission_train)
)

admission_model_tbl$.model_id <- c("poisson", "xgboost")
```

Prepare splits for CV


```{r}
#| label: make cv split

splits <- make_cv_splits(
  discharge_train,
  admission_train,
  h = 90,
  scheduled_admissions = scheduled_admissions
)
```

Run CV

```{r}
#| label: run cv
#| eval: !expr run_cv

discharge_results_cv <- fit_discharge_resamples(discharge_wflowset, splits)

admission_results_cv <- fit_admission_resamples(admission_model_tbl, splits$admission)

cv_results <- collect_cv_results(admission_results_cv, discharge_results_cv, splits)

save_data(cv_results, "manuscript/results/cv_results.rds")
```


```{r}
#| label: load cv
#| eval: !expr (!run_cv)
#| include: false

cv_results <- readRDS("manuscript/results/cv_results.rds")
```


```{r}
#| label: cv results

cv_results_summary <- cv_results |>
  select(admission_model, discharge_model, id, results) |>
  unnest(results) |>
  filter(.h %in% c(15, 30, 60, 90)) |>
  pivot_longer(
    matches("actual|pred"),
    names_to = c(".value", "stat"),
    names_pattern = "\\.(actual|pred)_(.+)"
  ) |>
  group_by(admission_model, discharge_model, stat, .h) |>
  rmse(actual, pred) |>
  filter(stat == "census")

cv_results_summary
```


```{r}
#| label: cv plot

cv_results_summary |>
  ggplot(aes(color = paste(admission_model, discharge_model, sep = "; "), y = .estimate, x = factor(.h))) +
  geom_point() +
  geom_line(aes(group = paste(admission_model, discharge_model))) +
  labs(y = "RMSE", x = "h (days ahead)", color = NULL)
```

## Tune

Discharge

```{r}
#| label: discharge tune setup

discharge_model_tune <- boost_tree(
  mode = "classification",
  sample_size = tune(),
  learn_rate = tune(),
  trees = 1000,
  min_n = tune(),
  mtry = tune()
)

params <- discharge_model_tune |>
  extract_parameter_set_dials() |>
  finalize(bake(prep(discharge_rec(discharge_train)), new_data = NULL))

discharge_wflowset_tune <- workflow_set(
  preproc = list(baseline = discharge_rec(discharge_train)),
  models = list(xgboost = discharge_model_tune)
) |>
  option_add(grid = 20, param_info = params)
```


```{r}
#| label: run discharge tune
#| eval: !expr run_tune

plan("multisession")

discharge_results_tune <- fit_discharge_resamples(discharge_wflowset_tune, splits)

plan("sequential")
```

Admission

```{r}
#| label: admission tune setup

admission_model_tune <- boost_tree(
  mode = "regression",
  trees = 1000,
  sample_size = tune(),
  learn_rate = tune(),
  min_n = tune(),
  mtry = tune()
) |>
  set_engine("xgboost", objective = "count:poisson")

admission_grid <- admission_model_tune |>
  extract_parameter_set_dials() |>
  finalize(juice(prep(admission_rec(admission_train, type = "xgb")))) |>
  grid_space_filling(size = 20)

admission_model_grid <- create_model_grid(
  grid = admission_grid,
  f_model_spec = boost_tree,
  engine_name = "xgboost",
  mode = "regression",
  trees = 1000,
  engine_params = list(objective = "count:poisson")
)
```


```{r}
#| label: run admission tune
#| eval: !expr run_tune

plan("multisession")

admission_model_tbl_tune <- workflow_set(
  preproc = list(admission_rec(admission_train, type = "xgb")),
  models = admission_model_grid$.models
) |>
  modeltime_fit_workflowset(data = admission_train, control = control_fit_workflowset(allow_par = TRUE))

admission_model_tbl_tune$.model_id <- "xgboost"
admission_model_tbl_tune$.config <- 1:nrow(admission_model_tbl_tune)
admission_model_tbl_tune$hyperparams <- admission_model_grid |>
  select(-.models) |>
  pmap(tibble)

admission_results_tune <- fit_admission_resamples(admission_model_tbl_tune, splits$admission)

plan("sequential")
```


```{r}
#| label: run tune sim
#| eval: !expr run_tune

plan("multisession")

tune_results <- collect_cv_results(admission_results_tune, discharge_results_tune, splits)

plan("sequential")

save_data(tune_results, "manuscript/results/tune_results.rds")
```

```{r}
#| label: load tune sim
#| eval: !expr (!run_tune)
#| include: false

tune_results <- readRDS("manuscript/results/tune_results.rds")
```


```{r}
#| label: tune results

mset <- metric_set(rmse, mape)

tune_results_summary <- tune_results |>
  rename(discharge = discharge_hyperparams, admission = admission_hyperparams) |>
  unnest(c(discharge, admission), names_sep = "_") |>
  unnest(results) |>
  filter(.h %in% c(15, 30, 60, 90)) |>
  pivot_longer(
    matches("actual|pred"),
    names_to = c(".value", "stat"),
    names_pattern = "\\.(actual|pred)_(.+)"
  ) |>
  group_by(admission_config, discharge_config, stat, .h, pick(matches("mtry|min_n|learn_rate|sample_size$"))) |>
  mset(actual, pred) |>
  filter(stat == "census")
```


```{r}
#| label: tune results mape plot

tune_results_summary |>
  filter(.metric == "mape") |>
  mutate(avg_estimate = mean(.estimate), .by = c(admission_config, discharge_config)) |>
  mutate(rank = rank(.estimate), .by = .h) |>
  mutate(avg_rank = dense_rank(avg_estimate)) |>
  filter(avg_rank <= 30) |>
  ggplot(aes(y = fct_rev(factor(avg_rank)), x = rank)) +
  geom_jitter(aes(color = factor(.h)), height = 0)
```


```{r}
#| label: tune results rmse plot

tune_results_summary |>
  filter(.metric == "rmse") |>
  mutate(avg_estimate = mean(.estimate), .by = c(admission_config, discharge_config)) |>
  mutate(rank = rank(.estimate), .by = .h) |>
  mutate(avg_rank = dense_rank(avg_estimate)) |>
  filter(avg_rank <= 30) |>
  ggplot(aes(y = fct_rev(factor(avg_rank)), x = rank)) +
  geom_jitter(aes(color = factor(.h)), height = 0)
```


```{r}
#| label: select best config

best_config <- tune_results_summary |> 
  filter(.metric == "rmse") |>
  mutate(avg_estimate = mean(.estimate), .by = c(admission_config, discharge_config)) |>
  filter(dense_rank(avg_estimate) == 1) |>
  distinct(admission_config, discharge_config)

final_params <- tune_results |>
  filter(
    discharge_config == best_config$discharge_config,
    admission_config == best_config$admission_config
  ) |>
  distinct(admission_hyperparams, discharge_hyperparams) |>
  as.list() |>
  map(pluck(1))

final_params
```

Fit models on training data

```{r}
#| label: fit on training
#| eval: !expr run_tune

discharge_model_train <- workflow(
  discharge_rec(discharge_train),
  discharge_model_tune
) |>
  finalize_workflow(final_params$discharge_hyperparams) |>
  fit(discharge_train)

admission_model_train <- workflow(
  admission_rec(admission_train, type = "xgb"),
  admission_model_tune
) |>
  finalize_workflow(final_params$admission_hyperparams) |>
  fit(admission_train) |>
  modeltime_table()

models_train <- bmt_model(discharge_model = discharge_model_train, admission_model = admission_model_train)

save_data(models_train, "manuscript/models/models_train.rds")
```

```{r}
#| label: load models_train
#| eval: !expr (!run_tune)
#| include: false

models_train <- readRDS("manuscript/models/models_train.rds")
```

## Test

```{r}
#| label: run test
#| eval: !expr run_test

test_dates <- unique(admission_test$date)

test_results <- make_test_data(test_dates, discharge_test, admission_test, scheduled_admissions)

test_results$results <- pmap(test_results, \(current_admissions, scheduled_admissions, ...) {
  predict_census(
    models = models_train,
    h = 1:90,
    current_census = current_admissions,
    scheduled_admissions = scheduled_admissions
  )
})

save_data(test_results, "manuscript/results/test_results.rds")
```

```{r}
#| label: load test
#| eval: !expr (!run_test)
#| include: false

test_results <- readRDS("manuscript/results/test_results.rds")
```

```{r}
#| label: test results summary

left_join(
    test_results |>
        select(test_date, results) |>
        unnest(results),
    test_results |>
        select(test_date, actual) |>
        unnest(actual),
    by = c("test_date", ".h")
) |>
    filter(.h %in% c(15, 30, 60, 90)) |>
    pivot_longer(
        matches("\\.(actual|pred)_"),
        names_to = c(".value", "stat"),
        names_pattern = "\\.(actual|pred)_(.+)"
    ) |>
    group_by(stat, .h) |>
    mset(actual, pred) |>
    filter(stat == "census")
```

```{r}
#| label: fit on full data
#| eval: !expr run_test

discharge_model_final <- fit(models_train$discharge, census_data)

admission_model_final <- modeltime_refit(models_train$admission, admission_data)

models_final <- bmt_model(discharge_model = discharge_model_final, admission_model = admission_model_final)

save_data(models_final, "manuscript/models/models_final.rds")
```


```{r}
#| label: load fit on full data
#| eval: !expr (!run_test)
#| include: false

models_final <- readRDS("manuscript/models/models_final.rds")
```